import React, { useEffect, useState } from 'react';
import { useParams, Link } from 'react-router-dom';
import blog1 from '../assets/blog1.jpg';
import blog2 from '../assets/blog2.webp';
import blog3 from '../assets/blog3.webp';

// Translations and RTL support
const translations = {
  en: {
    backToBlog: "Back to Blog",
    notFound: "Article Not Found",
    articles: [
      {
        id: 1,
        title: '5 Smart Ways to Save for Retirement',
        image: blog1,
        sections: [
          { heading: 'Early Planning', content: 'Starting early is crucial for retirement planning. Compound interest allows even small, regular contributions to grow significantly over time. By beginning in your 20s or 30s, you can take advantage of decades of growth, making it easier to reach your goals. Early planning also helps you develop good saving habits and reduces the pressure to save large amounts later in life.\n\nAdditionally, early savers can weather market downturns more easily and have more flexibility to adjust their plans. The earlier you start, the less you need to save each month to reach your retirement goals, making the process less stressful and more manageable.' },
          { heading: 'Employer-Sponsored Plans', content: 'Many employers offer retirement plans such as 401(k)s or pensions. Maximizing employer contributions and understanding vesting schedules can greatly enhance your retirement savings. These plans often provide tax advantages and may include investment options tailored for long-term growth.\n\nIt is important to review your plan options annually and increase your contributions as your salary grows. Missing out on employer matching is leaving free money on the table, so always contribute at least enough to get the full match.' },
          { heading: 'Diversification', content: 'A diversified portfolio reduces risk and increases the likelihood of stable returns. This includes a mix of stocks, bonds, mutual funds, and other assets. Diversification helps protect your savings from market volatility and ensures you are not overly reliant on a single investment.\n\nRebalancing your portfolio regularly ensures you maintain your desired asset allocation. Diversification is a key principle in modern portfolio theory and is recommended by most financial advisors.' },
          { heading: 'Tax-Advantaged Accounts', content: 'Utilizing IRAs, Roth IRAs, and other tax-advantaged accounts can help minimize tax liability and maximize growth. These accounts offer various benefits, such as tax-deferred or tax-free growth, and can be an essential part of your retirement strategy.\n\nUnderstanding the differences between account types and contribution limits is important. Take advantage of catch-up contributions if you are over 50, and consult a tax advisor for personalized advice.' },
          { heading: 'Managing Expenses', content: 'Budgeting for retirement involves estimating future expenses, including healthcare, housing, and leisure. Adjusting your savings rate as your income changes is recommended. Keeping track of your spending and planning for inflation can help ensure your savings last throughout retirement.\n\nUnexpected expenses can arise, so it is wise to build a buffer into your budget. Consider long-term care insurance and other ways to protect your nest egg.' },
          { heading: 'Professional Guidance', content: 'Consulting with a certified financial planner can help tailor a retirement plan to your specific needs and goals. Professionals can provide advice on investment choices, tax strategies, and risk management, helping you avoid common pitfalls.\n\nA good advisor will help you stay disciplined, avoid emotional decisions, and adjust your plan as your life circumstances change.' },
          { heading: 'Common Pitfalls', content: 'Avoiding high fees, emotional investing, and underestimating longevity risk are crucial for a successful retirement. Regularly reviewing your plan and making adjustments as needed can help you stay on track and achieve your retirement goals.\n\nOther pitfalls include withdrawing too much too soon, failing to plan for healthcare costs, and not updating your plan after major life events.' },
        ],
      },
      {
        id: 2,
        title: 'Understanding Credit Scores',
        image: blog2,
        sections: [
          { heading: 'Definition', content: 'A credit score is a three-digit number, typically ranging from 300 to 850, used by lenders to assess the risk of lending money to consumers. It is calculated based on your credit history and reflects your ability to repay debts.\n\nCredit scores are generated by credit bureaus using complex algorithms that analyze your borrowing and repayment behavior. They are a key factor in determining your eligibility for loans, credit cards, and even rental agreements.' },
          { heading: 'Components', content: 'The main factors influencing credit scores are payment history, amounts owed, length of credit history, new credit, and types of credit used. Each factor has a different weight, with payment history being the most significant.\n\nPayment history accounts for about 35% of your score, making timely payments essential. Amounts owed, or credit utilization, should be kept below 30% of your available credit. The length of your credit history shows lenders your experience with credit, while new credit and types of credit used add further depth to your profile.' },
          { heading: 'Importance', content: 'Credit scores affect loan approvals, interest rates, insurance premiums, and even employment opportunities. A higher score can save you money and open up more financial options.\n\nLenders use your score to assess risk, so a good score can help you qualify for larger loans and better terms. Some employers and landlords also check credit scores as part of their screening process.' },
          { heading: 'Improving Credit Scores', content: 'Timely payments, low credit utilization, and responsible management of credit accounts are key to improving scores. Avoiding late payments and reducing outstanding debt can have a positive impact.\n\nIt is also helpful to keep old accounts open, avoid applying for too much new credit at once, and regularly review your credit report for errors. Small, consistent improvements can add up over time.' },
          { heading: 'Monitoring and Errors', content: 'Regularly checking credit reports for errors and disputing inaccuracies is essential for maintaining a healthy score. Mistakes on your report can lower your score and affect your ability to get credit.\n\nYou are entitled to a free credit report from each major bureau every year. Review your reports for unfamiliar accounts, incorrect balances, or outdated information, and dispute any errors promptly.' },
          { heading: 'Building Credit', content: 'New consumers can build credit by using secured credit cards, becoming authorized users, or taking out small installment loans. Establishing a positive credit history early can benefit you in the long run.\n\nMaking small purchases and paying them off in full each month is a simple way to build a strong credit profile. Responsible use of credit is the foundation for a healthy financial future.' },
          { heading: 'Myths and Facts', content: 'Common myths include the belief that checking your own score lowers it, or that closing old accounts always helps. Understanding the facts can help you make better financial decisions.\n\nFor example, checking your own score is a soft inquiry and does not affect your score. Closing old accounts can actually lower your score by reducing your available credit and shortening your credit history.' },
        ],
      },
      {
        id: 3,
        title: 'Top 10 Investment Myths Busted',
        image: blog3,
        sections: [
          { heading: 'Investing is Only for the Wealthy', content: 'Modern platforms allow anyone to invest, regardless of income level. Fractional shares and low-cost funds have made investing accessible to all, breaking the myth that it is only for the rich.\n\nWith the rise of robo-advisors and commission-free trading, even small investors can build diversified portfolios. Many apps allow you to start investing with just a few dollars.' },
          { heading: 'You Need to Be an Expert', content: 'Accessible resources and index funds make investing possible for beginners. With a little research and discipline, anyone can start building wealth through investing.\n\nThere are countless books, online courses, and financial blogs that can help you learn the basics. Index funds and ETFs offer simple, low-cost ways to invest without needing to pick individual stocks.' },
          { heading: 'The Stock Market is Gambling', content: 'Investing is based on research and long-term growth, not chance. While there are risks, informed decisions and diversification can help manage them.\n\nUnlike gambling, investing is about owning a share of real businesses and benefiting from their growth. Over the long term, the stock market has historically provided positive returns.' },
          { heading: 'You Can Get Rich Quick', content: 'Sustainable investing is about patience and discipline, not quick wins. Chasing fast profits often leads to losses, while steady growth builds wealth over time.\n\nGet-rich-quick schemes are often scams or highly speculative. True wealth is built by investing consistently and letting your money grow over years or decades.' },
          { heading: 'All Debt is Bad', content: 'Some debt, like mortgages, can be leveraged for growth if managed wisely. Not all debt is harmful; it depends on how it is used and managed.\n\nGood debt can help you acquire appreciating assets, such as real estate or education, while bad debt, like high-interest credit cards, should be avoided.' },
          { heading: 'Timing the Market is Easy', content: 'Even professionals rarely time the market perfectly; consistent investing is more effective. Trying to predict market movements can lead to missed opportunities and losses.\n\nDollar-cost averaging, or investing a fixed amount at regular intervals, is a proven strategy for building wealth over time.' },
          { heading: 'You Should Always Avoid Risk', content: 'Risk is inherent in investing, but can be managed through diversification and research. Avoiding all risk can mean missing out on potential gains.\n\nUnderstanding your risk tolerance and investment goals is key. A well-diversified portfolio can help you achieve growth while managing downside risk.' },
        ],
      },
    ]
  },
  ar: {
    backToBlog: "العودة للمدونة",
    notFound: "المقال غير موجود",
    articles: [
      {
        id: 1,
        title: '٥ طرق ذكية للتوفير للتقاعد',
        image: blog1,
        sections: [
          { heading: 'التخطيط المبكر', content: 'بدء التخطيط مبكرًا أمر بالغ الأهمية للتقاعد. الفائدة المركبة تسمح حتى للمساهمات الصغيرة بالنمو بشكل كبير مع مرور الوقت. من خلال البدء في العشرينات أو الثلاثينات، يمكنك الاستفادة من عقود من النمو، مما يسهل تحقيق أهدافك.' },
          { heading: 'خطط التقاعد المقدمة من صاحب العمل', content: 'يقدم العديد من أصحاب العمل خطط تقاعد مثل 401(k) أو المعاشات. إن تعظيم مساهمات صاحب العمل وفهم جداول الاستحقاق يمكن أن يعزز بشكل كبير مدخرات التقاعد الخاصة بك.' },
          { heading: 'تنويع الاستثمارات', content: 'محفظة متنوعة تقلل من المخاطر وتزيد من احتمالية تحقيق عوائد مستقرة. يشمل ذلك مزيجًا من الأسهم والسندات وصناديق الاستثمار وغيرها من الأصول.' },
          { heading: 'الحسابات المعفاة من الضرائب', content: 'يمكن أن تساعد حسابات التقاعد مثل IRA و Roth IRA في تقليل الالتزام الضريبي وتعظيم النمو. تقدم هذه الحسابات مزايا مختلفة، مثل النمو المؤجل ضريبيًا أو المعفى من الضرائب.' },
          { heading: 'إدارة النفقات', content: 'يتضمن وضع ميزانية للتقاعد تقدير النفقات المستقبلية، بما في ذلك الرعاية الصحية والإسكان والترفيه. من المهم تعديل معدل المدخرات الخاص بك مع تغير دخلك.' },
          { heading: 'الإرشاد المهني', content: 'يمكن أن يساعدك التشاور مع مخطط مالي معتمد في تخصيص خطة تقاعد تناسب احتياجاتك وأهدافك المحددة. يمكن للمهنيين تقديم نصائح حول خيارات الاستثمار واستراتيجيات الضرائب وإدارة المخاطر.' },
          { heading: 'الأخطاء الشائعة', content: 'تجنب الرسوم العالية، والاستثمار العاطفي، وتقدير خطر طول العمر بشكل غير صحيح أمر بالغ الأهمية لتقاعد ناجح. يمكن أن تساعدك مراجعة خطتك بانتظام وإجراء التعديلات حسب الحاجة على البقاء على المسار الصحيح.' },
        ],
      },
      {
        id: 2,
        title: 'فهم درجات الائتمان',
        image: blog2,
        sections: [
          { heading: 'التعريف', content: 'درجة الائتمان هي رقم مكون من ثلاثة أرقام، يتراوح عادة بين 300 و 850، يستخدمه المقرضون لتقييم مخاطر إقراض المال للمستهلكين. يتم حسابها بناءً على تاريخك الائتماني وتعكس قدرتك على سداد الديون.' },
          { heading: 'المكونات', content: 'العوامل الرئيسية التي تؤثر على درجات الائتمان هي تاريخ الدفع، والمبالغ المستحقة، وطول التاريخ الائتماني، والائتمان الجديد، وأنواع الائتمان المستخدمة. لكل عامل وزن مختلف، مع كون تاريخ الدفع هو الأكثر أهمية.' },
          { heading: 'الأهمية', content: 'تؤثر درجات الائتمان على الموافقات على القروض، وأسعار الفائدة، وأقساط التأمين، وحتى فرص العمل. يمكن أن يوفر لك الحصول على درجة أعلى المال ويفتح لك المزيد من الخيارات المالية.' },
          { heading: 'تحسين درجات الائتمان', content: 'تعتبر المدفوعات في الوقت المحدد، واستخدام الائتمان المنخفض، والإدارة المسؤولة لحسابات الائتمان مفتاح تحسين الدرجات. تجنب المدفوعات المتأخرة وتقليل الديون المستحقة يمكن أن يكون له تأثير إيجابي.' },
          { heading: 'المراقبة والأخطاء', content: 'يعد التحقق بانتظام من تقارير الائتمان بحثًا عن الأخطاء وت disputing inaccuracies أمرًا ضروريًا للحفاظ على درجة صحية. يمكن أن تؤدي الأخطاء في تقريرك إلى خفض درجتك وتؤثر على قدرتك على الحصول على ائتمان.' },
          { heading: 'بناء الائتمان', content: 'يمكن للمستهلكين الجدد بناء الائتمان من خلال استخدام بطاقات الائتمان المضمونة، أو أن يصبحوا مستخدمين معتمدين، أو الحصول على قروض صغيرة بالتقسيط. يمكن أن يفيدك إنشاء تاريخ ائتماني إيجابي مبكرًا على المدى الطويل.' },
          { heading: 'الأساطير والحقائق', content: 'تشمل الأساطير الشائعة الاعتقاد بأن التحقق من درجتك الخاصة يقللها، أو أن إغلاق الحسابات القديمة دائمًا ما يساعد. يمكن أن تساعدك معرفة الحقائق في اتخاذ قرارات مالية أفضل.' },
        ],
      },
      {
        id: 3,
        title: 'أفضل 10 أساطير استثمار تم دحضها',
        image: blog3,
        sections: [
          { heading: 'الاستثمار متاح فقط للأثرياء', content: 'تسمح المنصات الحديثة لأي شخص بالاستثمار، بغض النظر عن مستوى الدخل. لقد جعلت الأسهم الجزئية والصناديق منخفضة التكلفة الاستثمار متاحًا للجميع، مما يكسر أسطورة أنه متاح فقط للأغنياء.' },
          { heading: 'يجب أن تكون خبيرًا', content: 'تجعل الموارد المتاحة وصناديق المؤشرات الاستثمار ممكنًا للمبتدئين. مع القليل من البحث والانضباط، يمكن لأي شخص البدء في بناء الثروة من خلال الاستثمار.' },
          { heading: 'سوق الأسهم هو قمار', content: 'الاستثمار يعتمد على البحث والنمو على المدى الطويل، وليس على الحظ. بينما توجد مخاطر، يمكن أن تساعد القرارات المستنيرة والتنويع في إدارتها.' },
          { heading: 'يمكنك أن تصبح ثريًا بسرعة', content: 'الاستثمار المستدام يتطلب الصبر والانضباط، وليس المكاسب السريعة. غالبًا ما تؤدي مطاردة الأرباح السريعة إلى خسائر، بينما يبني النمو الثابت الثروة بمرور الوقت.' },
          { heading: 'كل الديون سيئة', content: 'بعض الديون، مثل الرهون العقارية، يمكن أن تكون مفيدة للنمو إذا تمت إدارتها بحكمة. ليست كل الديون ضارة؛ يعتمد ذلك على كيفية استخدامها وإدارتها.' },
          { heading: 'توقيت السوق سهل', content: 'حتى المحترفين نادرًا ما ينجحون في توقيت السوق بشكل مثالي؛ الاستثمار المنتظم أكثر فعالية. يمكن أن يؤدي محاولة توقع تحركات السوق إلى تفويت الفرص والخسائر.' },
          { heading: 'يجب عليك دائمًا تجنب المخاطر', content: 'المخاطر جزء لا يتجزأ من الاستثمار، ولكن يمكن إدارتها من خلال التنويع والبحث. يمكن أن يعني تجنب كل المخاطر تفويت المكاسب المحتملة.' },
        ],
      },
    ]
  },
  he: {
    backToBlog: "חזרה לבלוג",
    notFound: "המאמר לא נמצא",
    articles: [] // Add Hebrew articles if available
  }
};

const BlogDetail = () => {
  const { id } = useParams();
  const [theme, setTheme] = useState(() => localStorage.getItem('theme') || 'light');
  const [language, setLanguage] = useState(() => localStorage.getItem('language') || 'en');

  useEffect(() => {
    const handleThemeChange = () => setTheme(localStorage.getItem('theme') || 'light');
    const handleLangChange = () => setLanguage(localStorage.getItem('language') || 'en');
    window.addEventListener('theme-changed', handleThemeChange);
    window.addEventListener('storage', handleThemeChange);
    window.addEventListener('language-changed', handleLangChange);
    window.addEventListener('focus', handleLangChange);
    return () => {
      window.removeEventListener('theme-changed', handleThemeChange);
      window.removeEventListener('storage', handleThemeChange);
      window.removeEventListener('language-changed', handleLangChange);
      window.removeEventListener('focus', handleLangChange);
    };
  }, []);

  // Language change handler
  const handleLanguageChange = (e) => {
    setLanguage(e.target.value);
    localStorage.setItem('language', e.target.value);
    window.dispatchEvent(new Event('language-changed'));
  };

  const t = translations[language] || translations['en'];
  // Fallback to English articles if current language has none
  const articles = t.articles && t.articles.length > 0 ? t.articles : translations['en'].articles;
  const isRTL = language === 'ar' || language === 'he';
  const article = articles.find(a => a.id === Number(id));

  if (!article) {
    return (
      <div className={`container mx-auto px-4 py-16 text-center min-h-screen ${theme === 'dark' ? 'bg-gray-900 text-gray-100' : 'bg-white text-black'}`} dir={isRTL ? 'rtl' : 'ltr'}>
        {/* Language Button */}
        <div style={{ position: 'absolute', top: 20, right: 20, zIndex: 100 }}>
          <select
            value={language}
            onChange={handleLanguageChange}
            className="px-3 py-2 rounded border border-gray-300 bg-white text-black"
          >
            <option value="en">English</option>
            <option value="ar">العربية</option>
            <option value="he">עברית</option>
          </select>
        </div>
        <h2 className="text-2xl font-bold mb-4">{t.notFound}</h2>
        <Link to="/blog" className="text-orange-500 hover:underline">{t.backToBlog}</Link>
      </div>
    );
  }

  return (
    <section
      className={`w-full min-h-screen transition-colors duration-300 ${theme === 'dark' ? 'bg-gray-900 text-gray-100' : 'bg-white text-black'}`}
      dir={isRTL ? 'rtl' : 'ltr'}
      style={{ position: 'relative' }}
    >
      {/* Language Button */}
      <div style={{ position: 'absolute', top: 20, right: 20, zIndex: 100 }}>
        <select
          value={language}
          onChange={handleLanguageChange}
          className="px-3 py-2 rounded border border-gray-300 bg-white text-black"
        >
          <option value="en">English</option>
          <option value="ar">العربية</option>
          <option value="he">עברית</option>
        </select>
      </div>
      <Link to="/blog" className="text-orange-500 font-semibold hover:underline block m-0 p-4">{isRTL ? '' : '←'} {t.backToBlog} {isRTL ? '→' : ''}</Link>
      <div className="w-full">
        <img src={article.image} alt={article.title} className="w-full max-h-[540px] md:max-h-[700px] object-cover object-center rounded-none shadow mb-0" />
      </div>
      <div className="w-full px-0 py-12">
        <h1 className="text-3xl font-bold pt-16 text-orange-500 mb-10 text-center">{article.title}</h1>
        <div className="flex flex-col gap-10 w-full px-4 md:px-24">
          {article.sections.map((section, idx) => (
            <div key={idx} className={`flex flex-col md:flex-row gap-6 md:gap-12 items-start w-full ${isRTL ? 'md:flex-row-reverse' : ''}`}>
              <div className={`md:w-1/3 w-full font-extrabold text-2xl md:text-3xl text-orange-500 mb-2 md:mb-0 ${isRTL ? 'md:text-left text-right pl-2 md:pl-6' : 'md:text-right text-left pr-2 md:pr-6'} flex-shrink-0`}>
                {section.heading}
              </div>
              <div className={`md:w-2/3 w-full text-base leading-relaxed whitespace-pre-line ${theme === 'dark' ? 'text-gray-200' : 'text-gray-800'}`}>
                {section.content}
              </div>
            </div>
          ))}
        </div>
        <Link to="/blog" className="text-orange-500 font-semibold hover:underline block mt-12 ml-4">{isRTL ? '' : '←'} {t.backToBlog} {isRTL ? '→' : ''}</Link>
      </div>
    </section>
  );
};

export default BlogDetail;